// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUqKRgbHBi85OcpDv2hMhCD0dMYNbKH_Y',
    appId: '1:645960663033:android:4bad7867ff88bba9834728',
    messagingSenderId: '645960663033',
    projectId: 'bjbanck',
    databaseURL: 'https://bjbanck-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bjbanck.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUop6jeVceEgsvLOsMr4CnefAO7y6Sc4Y',
    appId: '1:645960663033:ios:770193b410e60b2e834728',
    messagingSenderId: '645960663033',
    projectId: 'bjbanck',
    databaseURL: 'https://bjbanck-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bjbanck.firebasestorage.app',
    iosClientId: '645960663033-utkspkg19qira6coj468g7putacvgqic.apps.googleusercontent.com',
    iosBundleId: 'com.bjbank.ipg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrgBvpU5OZi4WC-8YYpHFmU3EIP4iWuUY',
    appId: '1:645960663033:web:22a5b4215edaf31b834728',
    messagingSenderId: '645960663033',
    projectId: 'bjbanck',
    authDomain: 'bjbanck.firebaseapp.com',
    databaseURL: 'https://bjbanck-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bjbanck.firebasestorage.app',
    measurementId: 'G-9052N42RKK',
  );

}